version: "3.3"

services:
  app_ocr:
    image: app-ocr:0.0.1
    hostname: app_ocr
    container_name: app_ocr
    environment:
      - PYTHONPATH=/home/ocr/python/ocr/
      - TZ=America/Sao_Paulo
      - TERM=xterm-256color
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 2G
    restart: always
    healthcheck:
      test: curl -f http://app_ocr:8000 || exit 1
      interval: 60s
      timeout: 15s
      retries: 5
    networks:
      - rede

networks:
  rede:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
