# https://docs.streamlit.io/library/advanced-features/configuration#set-configuration-options
# https://ecoagi.ai/pt/topics/Streamlit/streamlit-config 

[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

[server]
port = 8000
address = "0.0.0.0"
headless = true
enableCORS = false
maxCacheSize = 126 #MB

[browser]
gatherUsageStats = false

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.

# Default: 'info'
level = "info"

# Default: "%(asctime)s %(message)s"
messageFormat = "%(asctime)s %(message)s"