[theme]
base = "light"

[server]
port = 8000
address = "0.0.0.0"
headless = true
enableCORS = true

[browser]
gatherUsageStats = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"